vich_uploader:
    db_driver: orm
    mappings:
        site_map_image:
            uri_prefix: /images/site/map
            upload_destination: '%kernel.project_dir%/public/images/site/map'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        site_link_images:
            uri_prefix: /images/site/link
            upload_destination: '%kernel.project_dir%/public/images/site/link'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        gite_background_images:
            uri_prefix: /images/gite/background
            upload_destination: '%kernel.project_dir%/public/images/gite/background'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        gite_equipment_images:
            uri_prefix: /images/gite/equipment
            upload_destination: '%kernel.project_dir%/public/images/gite/equipment'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        gite_images:
            uri_prefix: /images/gite/image
            upload_destination: '%kernel.project_dir%/public/images/gite/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        service_images:
            uri_prefix: /images/service
            upload_destination: '%kernel.project_dir%/public/images/service'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
